---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adservice
  namespace: dev
  labels:
    app: adservice
spec:
  replicas: 5
  selector:
    matchLabels:
      app: adservice
  template:
    metadata:
      labels:
        app: adservice
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  namespace: dev
  name: aamer-service
spec:
  type: NodePort
  selector:
    app: adservice
  ports:
    - port: 80
      targetPort: 80
