apiVersion: v1
kind: Pod
metadata:
  name: nginx-web
  labels:
    app: nginx-webServer
    tier: frontend-Server
spec:
  containers:
    - name: container1
      image: nginx
    - name: container2
      image: busybox
