apiVersion: apps/v1
kind: Deployment
metadata:
  name: aamer-deployment
  labels:
    app: adservice
spec:
  replicas: 5
  selector:
    matchLabels:
      app: adservice
  template:
    metadata:
      labels:
        app: adservice
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
