apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-rs
  labels:
    app: controltower
    type: back-end
    environment: stg
    region: us-west-2
spec:
  template:
    metadata:
      name: "nginx-web-"
      labels:
        app: controltower
        type: back-end
        environment: stg
        region: us-west-2
    spec:
      containers:
        - name: control-tower-nginx-web01
          image: nginx
  replicas: 6
selector:
  matchLabels:
    type: back-end
