apiVersion: v1
kind: Pod
metadata:
  name: voting-app-pod
  labels:
    app: voting-app
    type: front-end
    category: web
    env: pro
spec:
  containers:
    - name: voting-app-container
      image: nginx
