apiVersion: v1
kind: Service
metadata:
  name: voteapp-app-svc
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30006
  selector:
    app: voting-app
    type: front-end
    category: web
    env: pro
