apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-frontend
  labels:
    app: voting-app
    type: front-end
    category: web
    env: pro
spec:
  template:
    metadata:
      name: voting-app-pod
      labels:
        app: voting-app
        type: front-end
        category: web
        env: pro
    spec:
      containers:
        - name: voting-app-container
          image: httpd:2.4-alpine
  replicas: 3
  selector:
    matchLabels:
      type: front-end
      env: pro
