apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: vote
  name: vote-deployment
  labels:
    app: voting-app
    env: pro
spec:
  replicas: 3
  selector:
    matchLabels:
      app: voting-app
      env: pro
  template:
    metadata:
      labels:
        app: voting-app
        env: pro
    spec:
      containers:
        - name: vote-container
          image: dockersamples/examplevotingapp_vote:before
          ports:
            - containerPort: 80
              name: voting-app
