apiVersion: v1
kind: Service
metadata:
  name: result-svc
  labels:
    app: result-svc
    env: pro
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30006
  selector:
    app: adservice
    env: pro
