apiVersion: v1
kind: Pod
metadata:
  name: result-pod
  labels:
    app: adservice
    env: pro
spec:
  containers:
    - name: result-app
      image: kodekloud/examplevotingapp_vote:v1
      ports:
        - containerPort: 80
