apiVersion: v1
kind: Service
metadata:
  name: adservice-svc
  labels:
    app: adservice-svc
    env: pro
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30005
  selector:
    app: adservice
    env: pro
