apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: adservice
    region: us-west-2
    environment: pro
spec:
  selector:
    matchLabels:
      app: adservice
      region: us-west-2
      environment: pro
  replicas: 4
  template:
    metadata:
      name: mypod
      labels:
        app: adservice
        region: us-west-2
        environment: pro
    spec:
      containers:
        - name: mypod-container
          image: nginx
