apiVersion: v1
kind: Pod
metadata:
  name: adservice
  labels:
    app: nginx-app
    tier: frontend
    environment: dev
    Service: AdService
spec:
  containers:
    - name: adservice-dev-container
      image: nginx
    - name: adservice-busybox-container
      image: busybox
