apiVersion: v1
kind: Pod
metadata:
  name: nginx-meta
  labels:
    app: nginx-app
    tier: frontend
spec:
  containers:
    - name: nginx-cont
      image: nginx
    - name: busybox-cont
      image: busybox
