apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
    region: us-west-2
    application: ad-service
    environment: dev
spec:
  containers:
    - name: nginx-container
      image: nginx
