apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-rc
  labels:
    application: adservice
    environment: pro
    region: us-west-2
spec:
  template:
    metadata:
      name: myapp-pod
      labels:
        application: adservice
        environment: pro
        region: us-west-2
    spec:
      containers:
        - name: nginx-containers
          image: nginx
  replicas: 3
