apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-replicaset
  labels:
    app: adservice
    environment: pro
spec:
  template:
    metadata:
      name: myapp-pod
      labels:
        app: adservice
        environment: pro
    spec:
      containers:
        - name: nginx-container
          image: nginx
  replicas: 3
  selector:
    matchLabels:
      app: adservice
      environment: pro
